-- World Cup 2026 Tracker - Seed Data
-- 980 stickers for the official Panini FIFA World Cup 2026 album
-- Run this AFTER schema.sql

INSERT INTO stickers (number, name, country, country_code, page_number, position_in_page, section_type) VALUES
  (1, 'Panini Logo', 'Panini', 'WP', 1, 1, 'special'),
  (2, 'Official Emblem  1/2', 'FIFA World Cup', 'FWC', 1, 2, 'special'),
  (3, 'Official Emblem  2/2', 'FIFA World Cup', 'FWC', 1, 3, 'special'),
  (4, 'Official Mascots', 'FIFA World Cup', 'FWC', 1, 4, 'special'),
  (5, 'Official Slogan', 'FIFA World Cup', 'FWC', 1, 5, 'special'),
  (6, 'Official Ball', 'FIFA World Cup', 'FWC', 1, 6, 'special'),
  (7, 'Canada', 'Host Country Emblem', 'FWC', 2, 1, 'special'),
  (8, 'Mexico', 'Host Country Emblem', 'FWC', 2, 2, 'special'),
  (9, 'USA', 'Host Country Emblem', 'FWC', 2, 3, 'special'),
  (10, 'Emblem', 'Algeria', 'ALG', 3, 1, 'regular'),
  (11, 'Alexis Guendouz', 'Algeria', 'ALG', 3, 2, 'regular'),
  (12, 'Ramy Bensebaini', 'Algeria', 'ALG', 3, 3, 'regular'),
  (13, 'Youcef Atal', 'Algeria', 'ALG', 3, 4, 'regular'),
  (14, 'Rayan Aït-Nouri', 'Algeria', 'ALG', 3, 5, 'regular'),
  (15, 'Mohamed Amine Tougai', 'Algeria', 'ALG', 3, 6, 'regular'),
  (16, 'Aïssa Mandi', 'Algeria', 'ALG', 3, 7, 'regular'),
  (17, 'Ismael Bennacer', 'Algeria', 'ALG', 3, 8, 'regular'),
  (18, 'Houssem Aquar', 'Algeria', 'ALG', 3, 9, 'regular'),
  (19, 'Hicham Boudaoui', 'Algeria', 'ALG', 3, 10, 'regular'),
  (20, 'Ramiz Zerrouki', 'Algeria', 'ALG', 4, 1, 'regular'),
  (21, 'Nabil Bentalab', 'Algeria', 'ALG', 4, 2, 'regular'),
  (22, 'Team Photo', 'Algeria', 'ALG', 4, 3, 'regular'),
  (23, 'Farés Chaibi', 'Algeria', 'ALG', 4, 4, 'regular'),
  (24, 'Riyad Mahrez', 'Algeria', 'ALG', 4, 5, 'regular'),
  (25, 'Said Benrhama', 'Algeria', 'ALG', 4, 6, 'regular'),
  (26, 'Anis Hadj Moussa', 'Algeria', 'ALG', 4, 7, 'regular'),
  (27, 'Amine Gouiri', 'Algeria', 'ALG', 4, 8, 'regular'),
  (28, 'Baghdad Bounedjah', 'Algeria', 'ALG', 4, 9, 'regular'),
  (29, 'Mohammed Amoura', 'Algeria', 'ALG', 4, 10, 'regular'),
  (30, 'Emblem', 'Argentina', 'ARG', 5, 1, 'regular'),
  (31, 'Emiliano Martinez', 'Argentina', 'ARG', 5, 2, 'regular'),
  (32, 'Nahuel Molina', 'Argentina', 'ARG', 5, 3, 'regular'),
  (33, 'Cristian Romero', 'Argentina', 'ARG', 5, 4, 'regular'),
  (34, 'Nicolas Otamendi', 'Argentina', 'ARG', 5, 5, 'regular'),
  (35, 'Nicolas Tagliafico', 'Argentina', 'ARG', 5, 6, 'regular'),
  (36, 'Leonardo Balerdi', 'Argentina', 'ARG', 5, 7, 'regular'),
  (37, 'Enzo Fernandez', 'Argentina', 'ARG', 5, 8, 'regular'),
  (38, 'Alexis Mac Allister', 'Argentina', 'ARG', 5, 9, 'regular'),
  (39, 'Rodrigo De Paul', 'Argentina', 'ARG', 5, 10, 'regular'),
  (40, 'Exequiel Palacios', 'Argentina', 'ARG', 6, 1, 'regular'),
  (41, 'Leandro Paredes', 'Argentina', 'ARG', 6, 2, 'regular'),
  (42, 'Team Photo', 'Argentina', 'ARG', 6, 3, 'regular'),
  (43, 'Nico Paz', 'Argentina', 'ARG', 6, 4, 'regular'),
  (44, 'Franco Mastantuono', 'Argentina', 'ARG', 6, 5, 'regular'),
  (45, 'Nico Gonzalez', 'Argentina', 'ARG', 6, 6, 'regular'),
  (46, 'Lionel Messi', 'Argentina', 'ARG', 6, 7, 'regular'),
  (47, 'Lautaro Martinez', 'Argentina', 'ARG', 6, 8, 'regular'),
  (48, 'Julian Alvarez', 'Argentina', 'ARG', 6, 9, 'regular'),
  (49, 'Giuliano Simeone', 'Argentina', 'ARG', 6, 10, 'regular'),
  (50, 'Emblem', 'Australia', 'AUS', 7, 1, 'regular'),
  (51, 'Mathew Ryan', 'Australia', 'AUS', 7, 2, 'regular'),
  (52, 'Joe Gauci', 'Australia', 'AUS', 7, 3, 'regular'),
  (53, 'Harry Souttar', 'Australia', 'AUS', 7, 4, 'regular'),
  (54, 'Alessandro Circati', 'Australia', 'AUS', 7, 5, 'regular'),
  (55, 'Jordan Bos', 'Australia', 'AUS', 7, 6, 'regular'),
  (56, 'Aziz Behich', 'Australia', 'AUS', 7, 7, 'regular'),
  (57, 'Cameron Burgess', 'Australia', 'AUS', 7, 8, 'regular'),
  (58, 'Lewis Miller', 'Australia', 'AUS', 7, 9, 'regular'),
  (59, 'Milos Degenek', 'Australia', 'AUS', 7, 10, 'regular'),
  (60, 'Jackson Irvine', 'Australia', 'AUS', 8, 1, 'regular'),
  (61, 'Riley McGree', 'Australia', 'AUS', 8, 2, 'regular'),
  (62, 'Team Photo', 'Australia', 'AUS', 8, 3, 'regular'),
  (63, 'Aiden O''Neill', 'Australia', 'AUS', 8, 4, 'regular'),
  (64, 'Connor Metcalfe', 'Australia', 'AUS', 8, 5, 'regular'),
  (65, 'Patrick Yazbek', 'Australia', 'AUS', 8, 6, 'regular'),
  (66, 'Craig Goodwin', 'Australia', 'AUS', 8, 7, 'regular'),
  (67, 'Kusini Vengi', 'Australia', 'AUS', 8, 8, 'regular'),
  (68, 'Nestory Irankunda', 'Australia', 'AUS', 8, 9, 'regular'),
  (69, 'Mohamed Touré', 'Australia', 'AUS', 8, 10, 'regular'),
  (70, 'Emblem', 'Austria', 'AUT', 9, 1, 'regular'),
  (71, 'Alexander Schlager', 'Austria', 'AUT', 9, 2, 'regular'),
  (72, 'Patrick Pentz', 'Austria', 'AUT', 9, 3, 'regular'),
  (73, 'David Alaba', 'Austria', 'AUT', 9, 4, 'regular'),
  (74, 'Kevin Danso', 'Austria', 'AUT', 9, 5, 'regular'),
  (75, 'Philipp Lienhart', 'Austria', 'AUT', 9, 6, 'regular'),
  (76, 'Stefan Bosch', 'Austria', 'AUT', 9, 7, 'regular'),
  (77, 'Phillipp Mwene', 'Austria', 'AUT', 9, 8, 'regular'),
  (78, 'Alexander Prass', 'Austria', 'AUT', 9, 9, 'regular'),
  (79, 'Xavier Schlager', 'Austria', 'AUT', 9, 10, 'regular'),
  (80, 'Marcel Sabitzer', 'Austria', 'AUT', 10, 1, 'regular'),
  (81, 'Konrad Laimer', 'Austria', 'AUT', 10, 2, 'regular'),
  (82, 'Team Photo', 'Austria', 'AUT', 10, 3, 'regular'),
  (83, 'Florian Grillitsch', 'Austria', 'AUT', 10, 4, 'regular'),
  (84, 'Nicolas Seiwald', 'Austria', 'AUT', 10, 5, 'regular'),
  (85, 'Romano Schmid', 'Austria', 'AUT', 10, 6, 'regular'),
  (86, 'Patrick Wimmer', 'Austria', 'AUT', 10, 7, 'regular'),
  (87, 'Christoph Baumgartner', 'Austria', 'AUT', 10, 8, 'regular'),
  (88, 'Michael Gregoritsch', 'Austria', 'AUT', 10, 9, 'regular'),
  (89, 'Marko Arnautović', 'Austria', 'AUT', 10, 10, 'regular'),
  (90, 'Emblem', 'Belgium', 'BEL', 11, 1, 'regular'),
  (91, 'Thibaut Courtois', 'Belgium', 'BEL', 11, 2, 'regular'),
  (92, 'Arthur Theate', 'Belgium', 'BEL', 11, 3, 'regular'),
  (93, 'Timothy Castagne', 'Belgium', 'BEL', 11, 4, 'regular'),
  (94, 'Zeno Debast', 'Belgium', 'BEL', 11, 5, 'regular'),
  (95, 'Brandon Mechele', 'Belgium', 'BEL', 11, 6, 'regular'),
  (96, 'Maxim De Cuyper', 'Belgium', 'BEL', 11, 7, 'regular'),
  (97, 'Thomas Meunier', 'Belgium', 'BEL', 11, 8, 'regular'),
  (98, 'Youri Tielemans', 'Belgium', 'BEL', 11, 9, 'regular'),
  (99, 'Amadou Onana', 'Belgium', 'BEL', 11, 10, 'regular'),
  (100, 'Nicolas Raskin', 'Belgium', 'BEL', 12, 1, 'regular'),
  (101, 'Alexis Saelemaekers', 'Belgium', 'BEL', 12, 2, 'regular'),
  (102, 'Team Photo', 'Belgium', 'BEL', 12, 3, 'regular'),
  (103, 'Hans Vanaken', 'Belgium', 'BEL', 12, 4, 'regular'),
  (104, 'Kevin De Bruyne', 'Belgium', 'BEL', 12, 5, 'regular'),
  (105, 'Jérémy Doku', 'Belgium', 'BEL', 12, 6, 'regular'),
  (106, 'Charles De Ketelaere', 'Belgium', 'BEL', 12, 7, 'regular'),
  (107, 'Leandro Trossard', 'Belgium', 'BEL', 12, 8, 'regular'),
  (108, 'Loïs Openda', 'Belgium', 'BEL', 12, 9, 'regular'),
  (109, 'Romelu Lukaku', 'Belgium', 'BEL', 12, 10, 'regular'),
  (110, 'Emblem', 'Bosnia and Herzegovina', 'BIH', 13, 1, 'regular'),
  (111, 'Nikola Vasilj', 'Bosnia and Herzegovina', 'BIH', 13, 2, 'regular'),
  (112, 'Amer Dedic', 'Bosnia and Herzegovina', 'BIH', 13, 3, 'regular'),
  (113, 'Sead Kolasinac', 'Bosnia and Herzegovina', 'BIH', 13, 4, 'regular'),
  (114, 'Tarik Muharemovic', 'Bosnia and Herzegovina', 'BIH', 13, 5, 'regular'),
  (115, 'Nihad Mujakic', 'Bosnia and Herzegovina', 'BIH', 13, 6, 'regular'),
  (116, 'Nikola Katic', 'Bosnia and Herzegovina', 'BIH', 13, 7, 'regular'),
  (117, 'Amir Hadziahmetovic', 'Bosnia and Herzegovina', 'BIH', 13, 8, 'regular'),
  (118, 'Benjamin Tahirovic', 'Bosnia and Herzegovina', 'BIH', 13, 9, 'regular'),
  (119, 'Armin Gigovic', 'Bosnia and Herzegovina', 'BIH', 13, 10, 'regular'),
  (120, 'Ivan Sunjic', 'Bosnia and Herzegovina', 'BIH', 14, 1, 'regular'),
  (121, 'Ivan Basic', 'Bosnia and Herzegovina', 'BIH', 14, 2, 'regular'),
  (122, 'Team Photo', 'Bosnia and Herzegovina', 'BIH', 14, 3, 'regular'),
  (123, 'Dzenis Burnic', 'Bosnia and Herzegovina', 'BIH', 14, 4, 'regular'),
  (124, 'Esmir Bajraktarevic', 'Bosnia and Herzegovina', 'BIH', 14, 5, 'regular'),
  (125, 'Amar Memic', 'Bosnia and Herzegovina', 'BIH', 14, 6, 'regular'),
  (126, 'Ermedin Demirovic', 'Bosnia and Herzegovina', 'BIH', 14, 7, 'regular'),
  (127, 'Edin Dzeko', 'Bosnia and Herzegovina', 'BIH', 14, 8, 'regular'),
  (128, 'Samed Bazdar', 'Bosnia and Herzegovina', 'BIH', 14, 9, 'regular'),
  (129, 'Haris Tabakovic', 'Bosnia and Herzegovina', 'BIH', 14, 10, 'regular'),
  (130, 'Emblem', 'Brazil', 'BRA', 15, 1, 'regular'),
  (131, 'Alisson', 'Brazil', 'BRA', 15, 2, 'regular'),
  (132, 'Bento', 'Brazil', 'BRA', 15, 3, 'regular'),
  (133, 'Marquinhos', 'Brazil', 'BRA', 15, 4, 'regular'),
  (134, 'Éder Militão', 'Brazil', 'BRA', 15, 5, 'regular'),
  (135, 'Gabriel Magalhães', 'Brazil', 'BRA', 15, 6, 'regular'),
  (136, 'Danilo', 'Brazil', 'BRA', 15, 7, 'regular'),
  (137, 'Wesley', 'Brazil', 'BRA', 15, 8, 'regular'),
  (138, 'Lucas Paquetá', 'Brazil', 'BRA', 15, 9, 'regular'),
  (139, 'Casemiro', 'Brazil', 'BRA', 15, 10, 'regular'),
  (140, 'Bruno Guimarães', 'Brazil', 'BRA', 16, 1, 'regular'),
  (141, 'Luiz Henrique', 'Brazil', 'BRA', 16, 2, 'regular'),
  (142, 'Team Photo', 'Brazil', 'BRA', 16, 3, 'regular'),
  (143, 'Vinicius Júnior', 'Brazil', 'BRA', 16, 4, 'regular'),
  (144, 'Rodrygo', 'Brazil', 'BRA', 16, 5, 'regular'),
  (145, 'João Pedro', 'Brazil', 'BRA', 16, 6, 'regular'),
  (146, 'Matheus Cunha', 'Brazil', 'BRA', 16, 7, 'regular'),
  (147, 'Gabriel Martinelli', 'Brazil', 'BRA', 16, 8, 'regular'),
  (148, 'Raphinha', 'Brazil', 'BRA', 16, 9, 'regular'),
  (149, 'Estévão', 'Brazil', 'BRA', 16, 10, 'regular'),
  (150, 'Emblem', 'Canada', 'CAN', 17, 1, 'regular'),
  (151, 'Dayne St.Clair', 'Canada', 'CAN', 17, 2, 'regular'),
  (152, 'Alphonso Davies', 'Canada', 'CAN', 17, 3, 'regular'),
  (153, 'Alistair Johnston', 'Canada', 'CAN', 17, 4, 'regular'),
  (154, 'Samuel Adekugbe', 'Canada', 'CAN', 17, 5, 'regular'),
  (155, 'Riche Larvea', 'Canada', 'CAN', 17, 6, 'regular'),
  (156, 'Derek Cornelius', 'Canada', 'CAN', 17, 7, 'regular'),
  (157, 'Moïse Bombito', 'Canada', 'CAN', 17, 8, 'regular'),
  (158, 'Kamal Miller', 'Canada', 'CAN', 17, 9, 'regular'),
  (159, 'Stephen Eustáquio', 'Canada', 'CAN', 17, 10, 'regular'),
  (160, 'Ismaël Koné', 'Canada', 'CAN', 18, 1, 'regular'),
  (161, 'Jonathan Osorio', 'Canada', 'CAN', 18, 2, 'regular'),
  (162, 'Team Photo', 'Canada', 'CAN', 18, 3, 'regular'),
  (163, 'Jacob Shaffelburg', 'Canada', 'CAN', 18, 4, 'regular'),
  (164, 'Mathieu Choinière', 'Canada', 'CAN', 18, 5, 'regular'),
  (165, 'Niko Sigur', 'Canada', 'CAN', 18, 6, 'regular'),
  (166, 'Tajon Buchanan', 'Canada', 'CAN', 18, 7, 'regular'),
  (167, 'Liam Millar', 'Canada', 'CAN', 18, 8, 'regular'),
  (168, 'Cyle Larin', 'Canada', 'CAN', 18, 9, 'regular'),
  (169, 'Jonathan David', 'Canada', 'CAN', 18, 10, 'regular'),
  (170, 'Emblem', 'Ivory Coast', 'CIV', 19, 1, 'regular'),
  (171, 'Yahia Fofana', 'Ivory Coast', 'CIV', 19, 2, 'regular'),
  (172, 'Ghislain Konan', 'Ivory Coast', 'CIV', 19, 3, 'regular'),
  (173, 'Wilfried Singo', 'Ivory Coast', 'CIV', 19, 4, 'regular'),
  (174, 'Odilon Kossounou', 'Ivory Coast', 'CIV', 19, 5, 'regular'),
  (175, 'Evan Ndicka', 'Ivory Coast', 'CIV', 19, 6, 'regular'),
  (176, 'Willy Boly', 'Ivory Coast', 'CIV', 19, 7, 'regular'),
  (177, 'Emmanuel Agbadou', 'Ivory Coast', 'CIV', 19, 8, 'regular'),
  (178, 'Ousmane Diomande', 'Ivory Coast', 'CIV', 19, 9, 'regular'),
  (179, 'Franck Kessie', 'Ivory Coast', 'CIV', 19, 10, 'regular'),
  (180, 'Seko Fofana', 'Ivory Coast', 'CIV', 20, 1, 'regular'),
  (181, 'Ibrahim Sangare', 'Ivory Coast', 'CIV', 20, 2, 'regular'),
  (182, 'Team Photo', 'Ivory Coast', 'CIV', 20, 3, 'regular'),
  (183, 'Jean-Philippe Gbamin', 'Ivory Coast', 'CIV', 20, 4, 'regular'),
  (184, 'Amad Diallo', 'Ivory Coast', 'CIV', 20, 5, 'regular'),
  (185, 'Sébastien Haller', 'Ivory Coast', 'CIV', 20, 6, 'regular'),
  (186, 'Simon Adringa', 'Ivory Coast', 'CIV', 20, 7, 'regular'),
  (187, 'Yan Diomande', 'Ivory Coast', 'CIV', 20, 8, 'regular'),
  (188, 'Evann Guessand', 'Ivory Coast', 'CIV', 20, 9, 'regular'),
  (189, 'Oumar Diakite', 'Ivory Coast', 'CIV', 20, 10, 'regular'),
  (190, 'Emblem', 'Congo DR', 'COD', 21, 1, 'regular'),
  (191, 'Lionel Mpasi', 'Congo DR', 'COD', 21, 2, 'regular'),
  (192, 'Aaron Wan-Bissaka', 'Congo DR', 'COD', 21, 3, 'regular'),
  (193, 'Axel Tuanzebe', 'Congo DR', 'COD', 21, 4, 'regular'),
  (194, 'Arthur Masuaku', 'Congo DR', 'COD', 21, 5, 'regular'),
  (195, 'Chancel Mbemba', 'Congo DR', 'COD', 21, 6, 'regular'),
  (196, 'Joris Kayembe', 'Congo DR', 'COD', 21, 7, 'regular'),
  (197, 'Charles Pickel', 'Congo DR', 'COD', 21, 8, 'regular'),
  (198, 'Ngal''ayel Mukau', 'Congo DR', 'COD', 21, 9, 'regular'),
  (199, 'Edo Kayembe', 'Congo DR', 'COD', 21, 10, 'regular'),
  (200, 'Samuel Moutoussamy', 'Congo DR', 'COD', 22, 1, 'regular'),
  (201, 'Noah Sadiki', 'Congo DR', 'COD', 22, 2, 'regular'),
  (202, 'Team Photo', 'Congo DR', 'COD', 22, 3, 'regular'),
  (203, 'Théo Bongonda', 'Congo DR', 'COD', 22, 4, 'regular'),
  (204, 'Meschak Elia', 'Congo DR', 'COD', 22, 5, 'regular'),
  (205, 'Yoane Wissa', 'Congo DR', 'COD', 22, 6, 'regular'),
  (206, 'Brian Cipenga', 'Congo DR', 'COD', 22, 7, 'regular'),
  (207, 'Fiston Mayele', 'Congo DR', 'COD', 22, 8, 'regular'),
  (208, 'Cédric Bakambu', 'Congo DR', 'COD', 22, 9, 'regular'),
  (209, 'Nathanaël Mbuku', 'Congo DR', 'COD', 22, 10, 'regular'),
  (210, 'Emblem', 'Colombia', 'COL', 23, 1, 'regular'),
  (211, 'Camilo Vargas', 'Colombia', 'COL', 23, 2, 'regular'),
  (212, 'David Ospina', 'Colombia', 'COL', 23, 3, 'regular'),
  (213, 'Dávinson Sánchez', 'Colombia', 'COL', 23, 4, 'regular'),
  (214, 'Yerry Mina', 'Colombia', 'COL', 23, 5, 'regular'),
  (215, 'Daniel Munoz', 'Colombia', 'COL', 23, 6, 'regular'),
  (216, 'Johan Mojica', 'Colombia', 'COL', 23, 7, 'regular'),
  (217, 'Jhon Lucumí', 'Colombia', 'COL', 23, 8, 'regular'),
  (218, 'Santiago Arias', 'Colombia', 'COL', 23, 9, 'regular'),
  (219, 'Jefferson Lerma', 'Colombia', 'COL', 23, 10, 'regular'),
  (220, 'Kevin Castaño', 'Colombia', 'COL', 24, 1, 'regular'),
  (221, 'Richard Rios', 'Colombia', 'COL', 24, 2, 'regular'),
  (222, 'Team Photo', 'Colombia', 'COL', 24, 3, 'regular'),
  (223, 'James Rodriguez', 'Colombia', 'COL', 24, 4, 'regular'),
  (224, 'Juan Fernando Quintero', 'Colombia', 'COL', 24, 5, 'regular'),
  (225, 'Jorge Carrascal', 'Colombia', 'COL', 24, 6, 'regular'),
  (226, 'Jhon Arias', 'Colombia', 'COL', 24, 7, 'regular'),
  (227, 'Jhon Cordova', 'Colombia', 'COL', 24, 8, 'regular'),
  (228, 'Luis Suarez', 'Colombia', 'COL', 24, 9, 'regular'),
  (229, 'Luis Diaz', 'Colombia', 'COL', 24, 10, 'regular'),
  (230, 'Emblem', 'Cape Verde', 'CPV', 25, 1, 'regular'),
  (231, 'Vozinha', 'Cape Verde', 'CPV', 25, 2, 'regular'),
  (232, 'Logan Costa', 'Cape Verde', 'CPV', 25, 3, 'regular'),
  (233, 'Pico', 'Cape Verde', 'CPV', 25, 4, 'regular'),
  (234, 'Diney', 'Cape Verde', 'CPV', 25, 5, 'regular'),
  (235, 'Steven Moreira', 'Cape Verde', 'CPV', 25, 6, 'regular'),
  (236, 'Wagner Pina', 'Cape Verde', 'CPV', 25, 7, 'regular'),
  (237, 'Joao Paulo', 'Cape Verde', 'CPV', 25, 8, 'regular'),
  (238, 'Yannick Semedo', 'Cape Verde', 'CPV', 25, 9, 'regular'),
  (239, 'Kevin Pina', 'Cape Verde', 'CPV', 25, 10, 'regular'),
  (240, 'Patrick Andrade', 'Cape Verde', 'CPV', 26, 1, 'regular'),
  (241, 'Jamiro Monteiro', 'Cape Verde', 'CPV', 26, 2, 'regular'),
  (242, 'Team Photo', 'Cape Verde', 'CPV', 26, 3, 'regular'),
  (243, 'Deroy Duarte', 'Cape Verde', 'CPV', 26, 4, 'regular'),
  (244, 'Garry Rodrigues', 'Cape Verde', 'CPV', 26, 5, 'regular'),
  (245, 'Jovane Cabral', 'Cape Verde', 'CPV', 26, 6, 'regular'),
  (246, 'Ryan Mendes', 'Cape Verde', 'CPV', 26, 7, 'regular'),
  (247, 'Dailon Livramento', 'Cape Verde', 'CPV', 26, 8, 'regular'),
  (248, 'Willy Semedo', 'Cape Verde', 'CPV', 26, 9, 'regular'),
  (249, 'Bebe', 'Cape Verde', 'CPV', 26, 10, 'regular'),
  (250, 'Emblem', 'Croatia', 'CRO', 27, 1, 'regular'),
  (251, 'Dominik Livaković', 'Croatia', 'CRO', 27, 2, 'regular'),
  (252, 'Duje Caleta-Car', 'Croatia', 'CRO', 27, 3, 'regular'),
  (253, 'Josko Gvardiol', 'Croatia', 'CRO', 27, 4, 'regular'),
  (254, 'Josip Stanišić', 'Croatia', 'CRO', 27, 5, 'regular'),
  (255, 'Luka Vušković', 'Croatia', 'CRO', 27, 6, 'regular'),
  (256, 'Josip Sutalo', 'Croatia', 'CRO', 27, 7, 'regular'),
  (257, 'Kristijan Jakic', 'Croatia', 'CRO', 27, 8, 'regular'),
  (258, 'Luka Modrić', 'Croatia', 'CRO', 27, 9, 'regular'),
  (259, 'Mateo Kovacic', 'Croatia', 'CRO', 27, 10, 'regular'),
  (260, 'Martin Baturina', 'Croatia', 'CRO', 28, 1, 'regular'),
  (261, 'Lovro Majer', 'Croatia', 'CRO', 28, 2, 'regular'),
  (262, 'Team Photo', 'Croatia', 'CRO', 28, 3, 'regular'),
  (263, 'Mario Pasalic', 'Croatia', 'CRO', 28, 4, 'regular'),
  (264, 'Petar Sucic', 'Croatia', 'CRO', 28, 5, 'regular'),
  (265, 'Ivan Perišić', 'Croatia', 'CRO', 28, 6, 'regular'),
  (266, 'Marco Pasalic', 'Croatia', 'CRO', 28, 7, 'regular'),
  (267, 'Ante Budimir', 'Croatia', 'CRO', 28, 8, 'regular'),
  (268, 'Andrej Kramarić', 'Croatia', 'CRO', 28, 9, 'regular'),
  (269, 'Franjo Ivanovic', 'Croatia', 'CRO', 28, 10, 'regular'),
  (270, 'Emblem', 'Curaçao', 'CUW', 29, 1, 'regular'),
  (271, 'Eloy Room', 'Curaçao', 'CUW', 29, 2, 'regular'),
  (272, 'Armando Obispo', 'Curaçao', 'CUW', 29, 3, 'regular'),
  (273, 'Sherel Floranus', 'Curaçao', 'CUW', 29, 4, 'regular'),
  (274, 'Jurien Gaari', 'Curaçao', 'CUW', 29, 5, 'regular'),
  (275, 'Joshua Brenet', 'Curaçao', 'CUW', 29, 6, 'regular'),
  (276, 'Roshon Van Eijma', 'Curaçao', 'CUW', 29, 7, 'regular'),
  (277, 'Shurandy Sambo', 'Curaçao', 'CUW', 29, 8, 'regular'),
  (278, 'Livano Comenencia', 'Curaçao', 'CUW', 29, 9, 'regular'),
  (279, 'Godfried Roemeratoe', 'Curaçao', 'CUW', 29, 10, 'regular'),
  (280, 'Juninho Bacuna', 'Curaçao', 'CUW', 30, 1, 'regular'),
  (281, 'Leandro Bacuna', 'Curaçao', 'CUW', 30, 1, 'regular'),
  (282, 'Team Photo', 'Curaçao', 'CUW', 30, 3, 'regular'),
  (283, 'Tahith Chong', 'Curaçao', 'CUW', 30, 4, 'regular'),
  (284, 'Kenji Gorre', 'Curaçao', 'CUW', 30, 5, 'regular'),
  (285, 'Jearl Margaritha', 'Curaçao', 'CUW', 30, 6, 'regular'),
  (286, 'Jurgen Locadia', 'Curaçao', 'CUW', 30, 7, 'regular'),
  (287, 'Jeremy Antonisse', 'Curaçao', 'CUW', 30, 8, 'regular'),
  (288, 'Gervane Kastaneer', 'Curaçao', 'CUW', 30, 9, 'regular'),
  (289, 'Sontje Hansen', 'Curaçao', 'CUW', 30, 10, 'regular'),
  (290, 'Emblem', 'Czechia', 'CZE', 31, 1, 'regular'),
  (291, 'Matej Kovar', 'Czechia', 'CZE', 31, 2, 'regular'),
  (292, 'Jindrich Stanek', 'Czechia', 'CZE', 31, 3, 'regular'),
  (293, 'Ladislav Krejci', 'Czechia', 'CZE', 31, 4, 'regular'),
  (294, 'Vladimir Coufal', 'Czechia', 'CZE', 31, 5, 'regular'),
  (295, 'Jaroslav Zeleny', 'Czechia', 'CZE', 31, 6, 'regular'),
  (296, 'Tomas Holes', 'Czechia', 'CZE', 31, 7, 'regular'),
  (297, 'David Zima', 'Czechia', 'CZE', 31, 8, 'regular'),
  (298, 'Michal Sadilek', 'Czechia', 'CZE', 31, 9, 'regular'),
  (299, 'Lukas Provod', 'Czechia', 'CZE', 31, 10, 'regular'),
  (300, 'Lukas Cerv', 'Czechia', 'CZE', 32, 1, 'regular'),
  (301, 'Tomas Soucek', 'Czechia', 'CZE', 32, 2, 'regular'),
  (302, 'Team Photo', 'Czechia', 'CZE', 32, 3, 'regular'),
  (303, 'Pavel Sulc', 'Czechia', 'CZE', 32, 4, 'regular'),
  (304, 'Matej Vydra', 'Czechia', 'CZE', 32, 5, 'regular'),
  (305, 'Vasil Kusej', 'Czechia', 'CZE', 32, 6, 'regular'),
  (306, 'Tomas Chory', 'Czechia', 'CZE', 32, 7, 'regular'),
  (307, 'Vacilav Cerny', 'Czechia', 'CZE', 32, 8, 'regular'),
  (308, 'Adam Hlozek', 'Czechia', 'CZE', 32, 9, 'regular'),
  (309, 'Patrik Schick', 'Czechia', 'CZE', 32, 10, 'regular'),
  (310, 'Emblem', 'Ecuador', 'ECU', 33, 1, 'regular'),
  (311, 'Hernán Galíndez', 'Ecuador', 'ECU', 33, 2, 'regular'),
  (312, 'Gonzalo Valle', 'Ecuador', 'ECU', 33, 3, 'regular'),
  (313, 'Piero Hincapié', 'Ecuador', 'ECU', 33, 4, 'regular'),
  (314, 'Pervis Estupiñán', 'Ecuador', 'ECU', 33, 5, 'regular'),
  (315, 'Willian Pacho', 'Ecuador', 'ECU', 33, 6, 'regular'),
  (316, 'Ángelo Preciado', 'Ecuador', 'ECU', 33, 7, 'regular'),
  (317, 'Joel Ordóñez', 'Ecuador', 'ECU', 33, 8, 'regular'),
  (318, 'Moises Caicedo', 'Ecuador', 'ECU', 33, 9, 'regular'),
  (319, 'Alan Franco', 'Ecuador', 'ECU', 33, 10, 'regular'),
  (320, 'Kendry Paez', 'Ecuador', 'ECU', 34, 1, 'regular'),
  (321, 'Pedro Vite', 'Ecuador', 'ECU', 34, 2, 'regular'),
  (322, 'Team Photo', 'Ecuador', 'ECU', 34, 3, 'regular'),
  (323, 'John Veboah', 'Ecuador', 'ECU', 34, 4, 'regular'),
  (324, 'Leonardo Campana', 'Ecuador', 'ECU', 34, 5, 'regular'),
  (325, 'Gonzalo Plata', 'Ecuador', 'ECU', 34, 6, 'regular'),
  (326, 'Nilson Angulo', 'Ecuador', 'ECU', 34, 7, 'regular'),
  (327, 'Alan Minda', 'Ecuador', 'ECU', 34, 8, 'regular'),
  (328, 'Kevin Rodriguez', 'Ecuador', 'ECU', 34, 9, 'regular'),
  (329, 'Enner Valencia', 'Ecuador', 'ECU', 34, 10, 'regular'),
  (330, 'Emblem', 'Egypt', 'EGY', 35, 1, 'regular'),
  (331, 'Mohamed El Shenawy', 'Egypt', 'EGY', 35, 2, 'regular'),
  (332, 'Mohamed Hany', 'Egypt', 'EGY', 35, 3, 'regular'),
  (333, 'Mohamed Hamdy', 'Egypt', 'EGY', 35, 4, 'regular'),
  (334, 'Yasser Ibrahim', 'Egypt', 'EGY', 35, 5, 'regular'),
  (335, 'Khaled Sobhi', 'Egypt', 'EGY', 35, 6, 'regular'),
  (336, 'Ramy Rabia', 'Egypt', 'EGY', 35, 7, 'regular'),
  (337, 'Hossam Abdelmaguid', 'Egypt', 'EGY', 35, 8, 'regular'),
  (338, 'Ahmed Fatouh', 'Egypt', 'EGY', 35, 9, 'regular'),
  (339, 'Marwan Attia', 'Egypt', 'EGY', 35, 10, 'regular'),
  (340, 'Zizo', 'Egypt', 'EGY', 36, 1, 'regular'),
  (341, 'Hamdy Fathy', 'Egypt', 'EGY', 36, 2, 'regular'),
  (342, 'Team Photo', 'Egypt', 'EGY', 36, 3, 'regular'),
  (343, 'Mohamed Lasheen', 'Egypt', 'EGY', 36, 4, 'regular'),
  (344, 'Emam Ashour', 'Egypt', 'EGY', 36, 5, 'regular'),
  (345, 'Osama Faisal', 'Egypt', 'EGY', 36, 6, 'regular'),
  (346, 'Mohamed Salah', 'Egypt', 'EGY', 36, 7, 'regular'),
  (347, 'Mostafa Mohamed', 'Egypt', 'EGY', 36, 8, 'regular'),
  (348, 'Trezeguet', 'Egypt', 'EGY', 36, 9, 'regular'),
  (349, 'Omar Marsmoush', 'Egypt', 'EGY', 36, 10, 'regular'),
  (350, 'Emblem', 'England', 'ENG', 37, 1, 'regular'),
  (351, 'Jordan Pickford', 'England', 'ENG', 37, 2, 'regular'),
  (352, 'John Stones', 'England', 'ENG', 37, 3, 'regular'),
  (353, 'Maric Guéhi', 'England', 'ENG', 37, 4, 'regular'),
  (354, 'Ezri Konsa', 'England', 'ENG', 37, 5, 'regular'),
  (355, 'Trent Alexander-Arnold', 'England', 'ENG', 37, 6, 'regular'),
  (356, 'Reece James', 'England', 'ENG', 37, 7, 'regular'),
  (357, 'Dan Burn', 'England', 'ENG', 37, 8, 'regular'),
  (358, 'Jordan Henderson', 'England', 'ENG', 37, 9, 'regular'),
  (359, 'Declan Rice', 'England', 'ENG', 37, 10, 'regular'),
  (360, 'Jude Bellingham', 'England', 'ENG', 38, 1, 'regular'),
  (361, 'Cole Palmer', 'England', 'ENG', 38, 2, 'regular'),
  (362, 'Team Photo', 'England', 'ENG', 38, 3, 'regular'),
  (363, 'Morgan Rogers', 'England', 'ENG', 38, 4, 'regular'),
  (364, 'Anthony Gordon', 'England', 'ENG', 38, 5, 'regular'),
  (365, 'Phil Foden', 'England', 'ENG', 38, 6, 'regular'),
  (366, 'Bukayo Saka', 'England', 'ENG', 38, 7, 'regular'),
  (367, 'Harry Kane', 'England', 'ENG', 38, 8, 'regular'),
  (368, 'Marcus Rashford', 'England', 'ENG', 38, 9, 'regular'),
  (369, 'Ollie Watkins', 'England', 'ENG', 38, 10, 'regular'),
  (370, 'Emblem', 'Spain', 'ESP', 39, 1, 'regular'),
  (371, 'Unai Simon', 'Spain', 'ESP', 39, 2, 'regular'),
  (372, 'Robin Le Normand', 'Spain', 'ESP', 39, 3, 'regular'),
  (373, 'Aymeric Laporte', 'Spain', 'ESP', 39, 4, 'regular'),
  (374, 'Dean Huijsen', 'Spain', 'ESP', 39, 5, 'regular'),
  (375, 'Pedro Porro', 'Spain', 'ESP', 39, 6, 'regular'),
  (376, 'Dani Carvajal', 'Spain', 'ESP', 39, 7, 'regular'),
  (377, 'Marc Cucurella', 'Spain', 'ESP', 39, 8, 'regular'),
  (378, 'Martín Zubimendi', 'Spain', 'ESP', 39, 9, 'regular'),
  (379, 'Rodri', 'Spain', 'ESP', 39, 10, 'regular'),
  (380, 'Pedri', 'Spain', 'ESP', 40, 1, 'regular'),
  (381, 'Fabian Ruiz', 'Spain', 'ESP', 40, 2, 'regular'),
  (382, 'Team Photo', 'Spain', 'ESP', 40, 3, 'regular'),
  (383, 'Mikel Merino', 'Spain', 'ESP', 40, 4, 'regular'),
  (384, 'Lamine Yamal', 'Spain', 'ESP', 40, 5, 'regular'),
  (385, 'Dani Olmo', 'Spain', 'ESP', 40, 6, 'regular'),
  (386, 'Nico Williams', 'Spain', 'ESP', 40, 7, 'regular'),
  (387, 'Ferran Torres', 'Spain', 'ESP', 40, 8, 'regular'),
  (388, 'Álvaro Morata', 'Spain', 'ESP', 40, 9, 'regular'),
  (389, 'Mikel Oyarzabal', 'Spain', 'ESP', 40, 10, 'regular'),
  (390, 'Emblem', 'France', 'FRA', 41, 1, 'regular'),
  (391, 'Mike Maignan', 'France', 'FRA', 41, 2, 'regular'),
  (392, 'Theo Hernandez', 'France', 'FRA', 41, 3, 'regular'),
  (393, 'William Saliba', 'France', 'FRA', 41, 4, 'regular'),
  (394, 'Jules Kounde', 'France', 'FRA', 41, 5, 'regular'),
  (395, 'Ibrahima Konate', 'France', 'FRA', 41, 6, 'regular'),
  (396, 'Dayot Upamecano', 'France', 'FRA', 41, 7, 'regular'),
  (397, 'Lucas Digne', 'France', 'FRA', 41, 8, 'regular'),
  (398, 'Aurélien Tchouaméni', 'France', 'FRA', 41, 9, 'regular'),
  (399, 'Eduardo Camavinga', 'France', 'FRA', 41, 10, 'regular'),
  (400, 'Manu Kone', 'France', 'FRA', 42, 1, 'regular'),
  (401, 'Adrien Rabiot', 'France', 'FRA', 42, 2, 'regular'),
  (402, 'Team Photo', 'France', 'FRA', 42, 3, 'regular'),
  (403, 'Michael Olise', 'France', 'FRA', 42, 4, 'regular'),
  (404, 'Ousmane Dembele', 'France', 'FRA', 42, 5, 'regular'),
  (405, 'Bradley Barcola', 'France', 'FRA', 42, 6, 'regular'),
  (406, 'Désiré Doué', 'France', 'FRA', 42, 7, 'regular'),
  (407, 'Kingsley Coman', 'France', 'FRA', 42, 8, 'regular'),
  (408, 'Hugo Ekitike', 'France', 'FRA', 42, 9, 'regular'),
  (409, 'Kylian Mbappe', 'France', 'FRA', 42, 10, 'regular'),
  (410, 'Emblem', 'Germany', 'GER', 43, 1, 'regular'),
  (411, 'Marc-André ter Stegen', 'Germany', 'GER', 43, 2, 'regular'),
  (412, 'Jonathan Tah', 'Germany', 'GER', 43, 3, 'regular'),
  (413, 'David Raum', 'Germany', 'GER', 43, 4, 'regular'),
  (414, 'Nico Schlotterbeck', 'Germany', 'GER', 43, 5, 'regular'),
  (415, 'Antonio Rüdiger', 'Germany', 'GER', 43, 6, 'regular'),
  (416, 'Waldemar Anton', 'Germany', 'GER', 43, 7, 'regular'),
  (417, 'Ridle Baku', 'Germany', 'GER', 43, 8, 'regular'),
  (418, 'Maximilian Mittelstadt', 'Germany', 'GER', 43, 9, 'regular'),
  (419, 'Joshua Kimmich', 'Germany', 'GER', 43, 10, 'regular'),
  (420, 'Florian Wirtz', 'Germany', 'GER', 44, 1, 'regular'),
  (421, 'Felix Nmecha', 'Germany', 'GER', 44, 2, 'regular'),
  (422, 'Team Photo', 'Germany', 'GER', 44, 3, 'regular'),
  (423, 'Leon Goretzka', 'Germany', 'GER', 44, 4, 'regular'),
  (424, 'Jamal Musiala', 'Germany', 'GER', 44, 5, 'regular'),
  (425, 'Serge Gnabry', 'Germany', 'GER', 44, 6, 'regular'),
  (426, 'Kai Havertz', 'Germany', 'GER', 44, 7, 'regular'),
  (427, 'Leroy Sane', 'Germany', 'GER', 44, 8, 'regular'),
  (428, 'Karim Adeyemi', 'Germany', 'GER', 44, 9, 'regular'),
  (429, 'Nick Woltemade', 'Germany', 'GER', 44, 10, 'regular'),
  (430, 'Emblem', 'Ghana', 'GHA', 45, 1, 'regular'),
  (431, 'Lawrence Ati Zigi', 'Ghana', 'GHA', 45, 2, 'regular'),
  (432, 'Tariq Lamptey', 'Ghana', 'GHA', 45, 3, 'regular'),
  (433, 'Mohammed Salisu', 'Ghana', 'GHA', 45, 4, 'regular'),
  (434, 'Alidu Seidu', 'Ghana', 'GHA', 45, 5, 'regular'),
  (435, 'Alexander Djiku', 'Ghana', 'GHA', 45, 6, 'regular'),
  (436, 'Gideon Mensah', 'Ghana', 'GHA', 45, 7, 'regular'),
  (437, 'Caleb Yirenkyi', 'Ghana', 'GHA', 45, 8, 'regular'),
  (438, 'Abdul Issahaku Fatawu', 'Ghana', 'GHA', 45, 9, 'regular'),
  (439, 'Thomas Partey', 'Ghana', 'GHA', 45, 10, 'regular'),
  (440, 'Salis Abdul Samed', 'Ghana', 'GHA', 46, 1, 'regular'),
  (441, 'Kamaldeen Sulemana', 'Ghana', 'GHA', 46, 2, 'regular'),
  (442, 'Team Photo', 'Ghana', 'GHA', 46, 3, 'regular'),
  (443, 'Mohammed Kudus', 'Ghana', 'GHA', 46, 4, 'regular'),
  (444, 'Inaki Williams', 'Ghana', 'GHA', 46, 5, 'regular'),
  (445, 'Jordan Ayew', 'Ghana', 'GHA', 46, 6, 'regular'),
  (446, 'Andrew Ayew', 'Ghana', 'GHA', 46, 7, 'regular'),
  (447, 'Joseph Paintsil', 'Ghana', 'GHA', 46, 8, 'regular'),
  (448, 'Osman Bukari', 'Ghana', 'GHA', 46, 9, 'regular'),
  (449, 'Antoine Semenyo', 'Ghana', 'GHA', 46, 10, 'regular'),
  (450, 'Emblem', 'Haiti', 'HAI', 47, 1, 'regular'),
  (451, 'Johny Placide', 'Haiti', 'HAI', 47, 2, 'regular'),
  (452, 'Carlens Arcus', 'Haiti', 'HAI', 47, 3, 'regular'),
  (453, 'Martin Expérience', 'Haiti', 'HAI', 47, 4, 'regular'),
  (454, 'Jean-Kevin Duverne', 'Haiti', 'HAI', 47, 5, 'regular'),
  (455, 'Ricardo Adé', 'Haiti', 'HAI', 47, 6, 'regular'),
  (456, 'Duke Lacroix', 'Haiti', 'HAI', 47, 7, 'regular'),
  (457, 'Garven Metusala', 'Haiti', 'HAI', 47, 8, 'regular'),
  (458, 'Hannes Delcroix', 'Haiti', 'HAI', 47, 9, 'regular'),
  (459, 'Leverton Pierre', 'Haiti', 'HAI', 47, 10, 'regular'),
  (460, 'Danley Jean Jacques', 'Haiti', 'HAI', 48, 1, 'regular'),
  (461, 'Jean-Ricner Bellegarde', 'Haiti', 'HAI', 48, 2, 'regular'),
  (462, 'Team Photo', 'Haiti', 'HAI', 48, 3, 'regular'),
  (463, 'Christopher Attys', 'Haiti', 'HAI', 48, 4, 'regular'),
  (464, 'Derrick Etienne Jr.', 'Haiti', 'HAI', 48, 5, 'regular'),
  (465, 'Josue Casimir', 'Haiti', 'HAI', 48, 6, 'regular'),
  (466, 'Ruben Providence', 'Haiti', 'HAI', 48, 7, 'regular'),
  (467, 'Duckens Nazon', 'Haiti', 'HAI', 48, 8, 'regular'),
  (468, 'Louicius Deedson', 'Haiti', 'HAI', 48, 9, 'regular'),
  (469, 'Frantzdy Pierrot', 'Haiti', 'HAI', 48, 10, 'regular'),
  (470, 'Emblem', 'Iran', 'IRN', 49, 1, 'regular'),
  (471, 'Alirez Beiranvand', 'Iran', 'IRN', 49, 2, 'regular'),
  (472, 'Morteza Pouraliganji', 'Iran', 'IRN', 49, 3, 'regular'),
  (473, 'Ehsan Hajsafi', 'Iran', 'IRN', 49, 4, 'regular'),
  (474, 'Milad Mohammadi', 'Iran', 'IRN', 49, 5, 'regular'),
  (475, 'Shojae Khalilzadeh', 'Iran', 'IRN', 49, 6, 'regular'),
  (476, 'Ramin Rezaeian', 'Iran', 'IRN', 49, 7, 'regular'),
  (477, 'Hossein Kanaani', 'Iran', 'IRN', 49, 8, 'regular'),
  (478, 'Sadegh Moharrami', 'Iran', 'IRN', 49, 9, 'regular'),
  (479, 'Saleh Hardani', 'Iran', 'IRN', 49, 10, 'regular'),
  (480, 'Saeed Ezatolahi', 'Iran', 'IRN', 50, 1, 'regular'),
  (481, 'Saman Ghoddos', 'Iran', 'IRN', 50, 2, 'regular'),
  (482, 'Team Photo', 'Iran', 'IRN', 50, 3, 'regular'),
  (483, 'Omid Noorafkan', 'Iran', 'IRN', 50, 4, 'regular'),
  (484, 'Roozbeh Cheshmi', 'Iran', 'IRN', 50, 5, 'regular'),
  (485, 'Mohammad Mohebi', 'Iran', 'IRN', 50, 6, 'regular'),
  (486, 'Sardar Azmoun', 'Iran', 'IRN', 50, 7, 'regular'),
  (487, 'Mehdi Taremi', 'Iran', 'IRN', 50, 8, 'regular'),
  (488, 'Alireza Jahanbakhsh', 'Iran', 'IRN', 50, 9, 'regular'),
  (489, 'Ali Gholizadeh', 'Iran', 'IRN', 50, 10, 'regular'),
  (490, 'Emblem', 'Iraq', 'IRQ', 51, 1, 'regular'),
  (491, 'Jalal Hassan', 'Iraq', 'IRQ', 51, 2, 'regular'),
  (492, 'Rebin Sulaka', 'Iraq', 'IRQ', 51, 3, 'regular'),
  (493, 'Hussein Ali', 'Iraq', 'IRQ', 51, 4, 'regular'),
  (494, 'Akam Hashem', 'Iraq', 'IRQ', 51, 5, 'regular'),
  (495, 'Merchas Doski', 'Iraq', 'IRQ', 51, 6, 'regular'),
  (496, 'Zaid Tahseen', 'Iraq', 'IRQ', 51, 7, 'regular'),
  (497, 'Manaf Younis', 'Iraq', 'IRQ', 51, 8, 'regular'),
  (498, 'Zidane Iqbal', 'Iraq', 'IRQ', 51, 9, 'regular'),
  (499, 'Amir Al-Ammari', 'Iraq', 'IRQ', 51, 10, 'regular'),
  (500, 'Ibrahim Bavesh', 'Iraq', 'IRQ', 52, 1, 'regular'),
  (501, 'Ali Jasim', 'Iraq', 'IRQ', 52, 2, 'regular'),
  (502, 'Team Photo', 'Iraq', 'IRQ', 52, 3, 'regular'),
  (503, 'Youssef Amyn', 'Iraq', 'IRQ', 52, 4, 'regular'),
  (504, 'Aimar Sher', 'Iraq', 'IRQ', 52, 5, 'regular'),
  (505, 'Marko Farji', 'Iraq', 'IRQ', 52, 6, 'regular'),
  (506, 'Osama Rashid', 'Iraq', 'IRQ', 52, 7, 'regular'),
  (507, 'Ali Al-Hamadi', 'Iraq', 'IRQ', 52, 8, 'regular'),
  (508, 'Aymen Hussein', 'Iraq', 'IRQ', 52, 9, 'regular'),
  (509, 'Mohanad Ali', 'Iraq', 'IRQ', 52, 10, 'regular'),
  (510, 'Emblem', 'Jordan', 'JOR', 53, 1, 'regular'),
  (511, 'Yazeed Abulaila', 'Jordan', 'JOR', 53, 2, 'regular'),
  (512, 'Ihsan Haddad', 'Jordan', 'JOR', 53, 3, 'regular'),
  (513, 'Mohammad Abu Hashish', 'Jordan', 'JOR', 53, 4, 'regular'),
  (514, 'Yazan Al-Arab', 'Jordan', 'JOR', 53, 5, 'regular'),
  (515, 'Abdallah Nasib', 'Jordan', 'JOR', 53, 6, 'regular'),
  (516, 'Saleem Obaid', 'Jordan', 'JOR', 53, 7, 'regular'),
  (517, 'Mohammad Abualnadi', 'Jordan', 'JOR', 53, 8, 'regular'),
  (518, 'Ibrahim Saadeh', 'Jordan', 'JOR', 53, 9, 'regular'),
  (519, 'Nizar Al-Rashdan', 'Jordan', 'JOR', 53, 10, 'regular'),
  (520, 'Noor Al-Rawabdeh', 'Jordan', 'JOR', 54, 1, 'regular'),
  (521, 'Mohannad Abu Taha', 'Jordan', 'JOR', 54, 2, 'regular'),
  (522, 'Team Photo', 'Jordan', 'JOR', 54, 3, 'regular'),
  (523, 'Amer Jamous', 'Jordan', 'JOR', 54, 4, 'regular'),
  (524, 'Mousa Al-Taamari', 'Jordan', 'JOR', 54, 5, 'regular'),
  (525, 'Yazan Al-Naimat', 'Jordan', 'JOR', 54, 6, 'regular'),
  (526, 'Mahmoud Al-Mardi', 'Jordan', 'JOR', 54, 7, 'regular'),
  (527, 'Ali Olwan', 'Jordan', 'JOR', 54, 8, 'regular'),
  (528, 'Mohammad Abu Zrayq', 'Jordan', 'JOR', 54, 9, 'regular'),
  (529, 'Ibrahim Sabra', 'Jordan', 'JOR', 54, 10, 'regular'),
  (530, 'Emblem', 'Japan', 'JPN', 55, 1, 'regular'),
  (531, 'Zion Suzuki', 'Japan', 'JPN', 55, 2, 'regular'),
  (532, 'Henry Heroki Mochizuki', 'Japan', 'JPN', 55, 3, 'regular'),
  (533, 'Ayumu Seko', 'Japan', 'JPN', 55, 4, 'regular'),
  (534, 'Junnosuke Suzuki', 'Japan', 'JPN', 55, 5, 'regular'),
  (535, 'Shogo Taniguchi', 'Japan', 'JPN', 55, 6, 'regular'),
  (536, 'Tsuyoshi Watanabe', 'Japan', 'JPN', 55, 7, 'regular'),
  (537, 'Kaishu Sano', 'Japan', 'JPN', 55, 8, 'regular'),
  (538, 'Yuki Soma', 'Japan', 'JPN', 55, 9, 'regular'),
  (539, 'Ao Tanaka', 'Japan', 'JPN', 55, 10, 'regular'),
  (540, 'Daichi Kamada', 'Japan', 'JPN', 56, 1, 'regular'),
  (541, 'Takefusa Kubo', 'Japan', 'JPN', 56, 2, 'regular'),
  (542, 'Team Photo', 'Japan', 'JPN', 56, 3, 'regular'),
  (543, 'Ritsu Doan', 'Japan', 'JPN', 56, 4, 'regular'),
  (544, 'Keito Nakamura', 'Japan', 'JPN', 56, 5, 'regular'),
  (545, 'Takumi Minamino', 'Japan', 'JPN', 56, 6, 'regular'),
  (546, 'Shuto Machino', 'Japan', 'JPN', 56, 7, 'regular'),
  (547, 'Junya Ito', 'Japan', 'JPN', 56, 8, 'regular'),
  (548, 'Koki Ogawa', 'Japan', 'JPN', 56, 9, 'regular'),
  (549, 'Ayase Ueda', 'Japan', 'JPN', 56, 10, 'regular'),
  (550, 'Emblem', 'South Korea', 'KOR', 57, 1, 'regular'),
  (551, 'Hyeon-woo Jo', 'South Korea', 'KOR', 57, 2, 'regular'),
  (552, 'Seung-Gyu Kim', 'South Korea', 'KOR', 57, 3, 'regular'),
  (553, 'Min-jae Kim', 'South Korea', 'KOR', 57, 4, 'regular'),
  (554, 'Yu-min Cho', 'South Korea', 'KOR', 57, 5, 'regular'),
  (555, 'Young-woo Seol', 'South Korea', 'KOR', 57, 6, 'regular'),
  (556, 'Han-beom Lee', 'South Korea', 'KOR', 57, 7, 'regular'),
  (557, 'Tae-seok Lee', 'South Korea', 'KOR', 57, 8, 'regular'),
  (558, 'Myung-jae Lee', 'South Korea', 'KOR', 57, 9, 'regular'),
  (559, 'Jae-sung Lee', 'South Korea', 'KOR', 57, 10, 'regular'),
  (560, 'In-beom Hwang', 'South Korea', 'KOR', 58, 1, 'regular'),
  (561, 'Kang-in Lee', 'South Korea', 'KOR', 58, 2, 'regular'),
  (562, 'Team Photo', 'South Korea', 'KOR', 58, 3, 'regular'),
  (563, 'Seung-ho Paik', 'South Korea', 'KOR', 58, 4, 'regular'),
  (564, 'Jens Castrop', 'South Korea', 'KOR', 58, 5, 'regular'),
  (565, 'Dongg-yeong Lee', 'South Korea', 'KOR', 58, 6, 'regular'),
  (566, 'Gue-sung Cho', 'South Korea', 'KOR', 58, 7, 'regular'),
  (567, 'Heung-min Son', 'South Korea', 'KOR', 58, 8, 'regular'),
  (568, 'Hee-chan Hwang', 'South Korea', 'KOR', 58, 9, 'regular'),
  (569, 'Hyeon-Gyu Oh', 'South Korea', 'KOR', 58, 10, 'regular'),
  (570, 'Emblem', 'Saudi Arabia', 'KSA', 59, 1, 'regular'),
  (571, 'Nawaf Alaqidi', 'Saudi Arabia', 'KSA', 59, 2, 'regular'),
  (572, 'Abdulrahman Al-Sanbi', 'Saudi Arabia', 'KSA', 59, 3, 'regular'),
  (573, 'Saud Abdulhamid', 'Saudi Arabia', 'KSA', 59, 4, 'regular'),
  (574, 'Nawaf Bouwashl', 'Saudi Arabia', 'KSA', 59, 5, 'regular'),
  (575, 'Jihad Thakri', 'Saudi Arabia', 'KSA', 59, 6, 'regular'),
  (576, 'Moteb Al-Harbi', 'Saudi Arabia', 'KSA', 59, 7, 'regular'),
  (577, 'Hassan Altambakti', 'Saudi Arabia', 'KSA', 59, 8, 'regular'),
  (578, 'Musab Aljuwayr', 'Saudi Arabia', 'KSA', 59, 9, 'regular'),
  (579, 'Ziyad Aljohani', 'Saudi Arabia', 'KSA', 59, 10, 'regular'),
  (580, 'Abdullah Alkhaibari', 'Saudi Arabia', 'KSA', 60, 1, 'regular'),
  (581, 'Nasser Aldawsari (Saudi Arabia', 'KSA', 'KSA', 60, 2, 'regular'),
  (582, 'Team Photo', 'Saudi Arabia', 'KSA', 60, 3, 'regular'),
  (583, 'Saleh Abu Alshamat', 'Saudi Arabia', 'KSA', 60, 4, 'regular'),
  (584, 'Marwan Alsahafi', 'Saudi Arabia', 'KSA', 60, 5, 'regular'),
  (585, 'Salem Aldawsari', 'Saudi Arabia', 'KSA', 60, 6, 'regular'),
  (586, 'Abdulrahman Al-Aboud', 'Saudi Arabia', 'KSA', 60, 7, 'regular'),
  (587, 'Feras Akbrikan', 'Saudi Arabia', 'KSA', 60, 8, 'regular'),
  (588, 'Saleh Alshehri', 'Saudi Arabia', 'KSA', 60, 9, 'regular'),
  (589, 'Abdullah Al-Hamdan', 'Saudi Arabia', 'KSA', 60, 10, 'regular'),
  (590, 'Emblem', 'Morocco', 'MAR', 61, 1, 'regular'),
  (591, 'Yassine Bounou', 'Morocco', 'MAR', 61, 2, 'regular'),
  (592, 'Munir El Kajoui', 'Morrocco', 'MAR', 61, 3, 'regular'),
  (593, 'Achraf Hakimi', 'Morocco', 'MAR', 61, 4, 'regular'),
  (594, 'Noussair Mazraoui', 'Morocco', 'MAR', 61, 5, 'regular'),
  (595, 'Nayef Aguerd', 'Morocco', 'MAR', 61, 6, 'regular'),
  (596, 'Roman Saiss', 'Morocco', 'MAR', 61, 7, 'regular'),
  (597, 'Jawad El Yamio', 'Morocco', 'MAR', 61, 8, 'regular'),
  (598, 'Adam Masina', 'Morocco', 'MAR', 61, 9, 'regular'),
  (599, 'Sofyan Amrabat', 'Morocco', 'MAR', 61, 10, 'regular'),
  (600, 'Azzedine Ounahi', 'Morrocco', 'MAR', 62, 1, 'regular'),
  (601, 'Eliesse Ben Seghir', 'Morocco', 'MAR', 62, 2, 'regular'),
  (602, 'Team Photo', 'Morocco', 'MAR', 62, 3, 'regular'),
  (603, 'Bilal El Khannouss', 'Morocco', 'MAR', 62, 4, 'regular'),
  (604, 'Ismael Saibari', 'Morocco', 'MAR', 62, 5, 'regular'),
  (605, 'Youssef En-Nesyri', 'Morocco', 'MAR', 62, 6, 'regular'),
  (606, 'Abde Ezzalzouli', 'Morocco', 'MAR', 62, 7, 'regular'),
  (607, 'Soufiane Rahimi', 'Morocco', 'MAR', 62, 8, 'regular'),
  (608, 'Brahim Diaz', 'Morocco', 'MAR', 62, 9, 'regular'),
  (609, 'Ayoub El Kaabi', 'Morocco', 'MAR', 62, 10, 'regular'),
  (610, 'Emblem', 'Mexico', 'MEX', 63, 1, 'regular'),
  (611, 'Luis Malagón', 'Mexico', 'MEX', 63, 2, 'regular'),
  (612, 'Johan Vasquez', 'Mexico', 'MEX', 63, 3, 'regular'),
  (613, 'Jorge Sánchez', 'Mexico', 'MEX', 63, 4, 'regular'),
  (614, 'Cesar Montes', 'Mexico', 'MEX', 63, 5, 'regular'),
  (615, 'Jesus Gallardo', 'Mexico', 'MEX', 63, 6, 'regular'),
  (616, 'Israel Reyes', 'Mexico', 'MEX', 63, 7, 'regular'),
  (617, 'Diego Lainez', 'Mexico', 'MEX', 63, 8, 'regular'),
  (618, 'Carlos Rodriguez', 'Mexico', 'MEX', 63, 9, 'regular'),
  (619, 'Edson Alvarez', 'Mexico', 'MEX', 63, 10, 'regular'),
  (620, 'Orbelin Pineda', 'Mexico', 'MEX', 64, 1, 'regular'),
  (621, 'Marcel Ruiz', 'Mexico', 'MEX', 64, 2, 'regular'),
  (622, 'Team Photo', 'Mexico', 'MEX', 64, 3, 'regular'),
  (623, 'Érick Sánchez', 'Mexico', 'MEX', 64, 4, 'regular'),
  (624, 'Hirving Lozano', 'Mexico', 'MEX', 64, 5, 'regular'),
  (625, 'Santiago Giménez', 'Mexico', 'MEX', 64, 6, 'regular'),
  (626, 'Raúl Jiménez', 'Mexico', 'MEX', 64, 7, 'regular'),
  (627, 'Alexis Vega', 'Mexico', 'MEX', 64, 8, 'regular'),
  (628, 'Roberto Alvarado', 'Mexico', 'MEX', 64, 9, 'regular'),
  (629, 'Cesar Huerta', 'Mexico', 'MEX', 64, 10, 'regular'),
  (630, 'Emblem', 'Netherlands', 'NED', 65, 1, 'regular'),
  (631, 'Bart Verbruggen', 'Netherlands', 'NED', 65, 2, 'regular'),
  (632, 'Virgil van Dijk', 'Netherlands', 'NED', 65, 3, 'regular'),
  (633, 'Micky van de Ven', 'Netherlands', 'NED', 65, 4, 'regular'),
  (634, 'Jurien Timber', 'Netherlands', 'NED', 65, 5, 'regular'),
  (635, 'Denzel Dumfries', 'Netherlands', 'NED', 65, 6, 'regular'),
  (636, 'Nathan Aké', 'Netherlands', 'NED', 65, 7, 'regular'),
  (637, 'Jereme Frimpong', 'Netherlands', 'NED', 65, 8, 'regular'),
  (638, 'Jan Paul van Hecke', 'Netherlands', 'NED', 65, 9, 'regular'),
  (639, 'Tijjani Reijnders', 'Netherlands', 'NED', 65, 10, 'regular'),
  (640, 'Ryan Gravenberch', 'Netherlands', 'NED', 66, 1, 'regular'),
  (641, 'Teun Koopmeiners', 'Netherlands', 'NED', 66, 2, 'regular'),
  (642, 'Team Photo', 'Netherlands', 'NED', 66, 3, 'regular'),
  (643, 'Frenkie de Jong', 'Netherlands', 'NED', 66, 4, 'regular'),
  (644, 'Xavi Simons', 'Netherlands', 'NED', 66, 5, 'regular'),
  (645, 'Justin Kluivert', 'Netherlands', 'NED', 66, 6, 'regular'),
  (646, 'Memphis Depay', 'Netherlands', 'NED', 66, 7, 'regular'),
  (647, 'Donyell Malen', 'Netherlands', 'NED', 66, 8, 'regular'),
  (648, 'Wout Weghorst', 'Netherlands', 'NED', 66, 9, 'regular'),
  (649, 'Cody Gakpo', 'Netherlands', 'NED', 66, 10, 'regular'),
  (650, 'Emblem', 'Norway', 'NOR', 67, 1, 'regular'),
  (651, 'Orjan Nyland', 'Norway', 'NOR', 67, 2, 'regular'),
  (652, 'Julian Ryerson', 'Norway', 'NOR', 67, 3, 'regular'),
  (653, 'Leo Ostigård', 'Norway', 'NOR', 67, 4, 'regular'),
  (654, 'Kristoffer Vassbakk Ajer', 'Norway', 'NOR', 67, 5, 'regular'),
  (655, 'Marcus Holmgren Pedersen', 'Norway', 'NOR', 67, 6, 'regular'),
  (656, 'David Møller Wolfe', 'Norway', 'NOR', 67, 7, 'regular'),
  (657, 'Torbjørn Heggem', 'Norway', 'NOR', 67, 8, 'regular'),
  (658, 'Morten Thorsby', 'Norway', 'NOR', 67, 9, 'regular'),
  (659, 'Martin Ødegaard', 'Norway', 'NOR', 67, 10, 'regular'),
  (660, 'Sander Berge', 'Norway', 'NOR', 68, 1, 'regular'),
  (661, 'Andreas Schjelderup', 'Norway', 'NOR', 68, 2, 'regular'),
  (662, 'Team Photo', 'Norway', 'NOR', 68, 3, 'regular'),
  (663, 'Patrick Berg', 'Norway', 'NOR', 68, 4, 'regular'),
  (664, 'Erling Haaland', 'Norway', 'NOR', 68, 5, 'regular'),
  (665, 'Alexander Sørloth', 'Norway', 'NOR', 68, 6, 'regular'),
  (666, 'Aron Dønnum', 'Norway', 'NOR', 68, 7, 'regular'),
  (667, 'Jorgen Strand Larsen', 'Norway', 'NOR', 68, 8, 'regular'),
  (668, 'Antonio Nusa', 'Norway', 'NOR', 68, 9, 'regular'),
  (669, 'Oscar Bobb', 'Norway', 'NOR', 68, 10, 'regular'),
  (670, 'Emblem', 'New Zealand', 'NZL', 69, 1, 'regular'),
  (671, 'Max Crocombe Payne', 'New Zealand', 'NZL', 69, 2, 'regular'),
  (672, 'Alex Paulsen', 'New Zealand', 'NZL', 69, 3, 'regular'),
  (673, 'Michael Boxall', 'New Zealand', 'NZL', 69, 4, 'regular'),
  (674, 'Liberato Cacace', 'New Zealand', 'NZL', 69, 5, 'regular'),
  (675, 'Tim Payne', 'New Zealand', 'NZL', 69, 6, 'regular'),
  (676, 'Tyler Bindon', 'New Zealand', 'NZL', 69, 7, 'regular'),
  (677, 'Francis de Vries', 'New Zealand', 'NZL', 69, 8, 'regular'),
  (678, 'Finn Surman', 'New Zealand', 'NZL', 69, 9, 'regular'),
  (679, 'Joe Bell', 'New Zealand', 'NZL', 69, 10, 'regular'),
  (680, 'Sarpreet Singh', 'New Zealand', 'NZL', 70, 1, 'regular'),
  (681, 'Ryan Thomas', 'New Zealand', 'NZL', 70, 2, 'regular'),
  (682, 'Team Photo', 'New Zealand', 'NZL', 70, 3, 'regular'),
  (683, 'Matthew Garbett', 'New Zealand', 'NZL', 70, 4, 'regular'),
  (684, 'Marko Stamenić', 'New Zealand', 'NZL', 70, 5, 'regular'),
  (685, 'Ben Old', 'New Zealand', 'NZL', 70, 6, 'regular'),
  (686, 'Chris Wood', 'New Zealand', 'NZL', 70, 7, 'regular'),
  (687, 'Elijah Just', 'New Zealand', 'NZL', 70, 8, 'regular'),
  (688, 'Callum McCowatt', 'New Zealand', 'NZL', 70, 9, 'regular'),
  (689, 'Kosta Barbarouses', 'New Zealand', 'NZL', 70, 10, 'regular'),
  (690, 'Emblem', 'Panama', 'PAN', 71, 1, 'regular'),
  (691, 'Orlando Mosquera', 'Panama', 'PAN', 71, 2, 'regular'),
  (692, 'Luis Mejia', 'Panama', 'PAN', 71, 3, 'regular'),
  (693, 'Fidel Escobar', 'Panama', 'PAN', 71, 4, 'regular'),
  (694, 'Andres Andrade', 'Panama', 'PAN', 71, 5, 'regular'),
  (695, 'Michael Amir Murillo', 'Panama', 'PAN', 71, 6, 'regular'),
  (696, 'Eric Davis', 'Panama', 'PAN', 71, 7, 'regular'),
  (697, 'Jose Cordoba', 'Panama', 'PAN', 71, 8, 'regular'),
  (698, 'Cesar Blackman', 'Panama', 'PAN', 71, 9, 'regular'),
  (699, 'Cristian Martinez', 'Panama', 'PAN', 71, 10, 'regular'),
  (700, 'Aníbal Godoy', 'Panama', 'PAN', 72, 1, 'regular'),
  (701, 'Adalberto Carrasquilla', 'Panama', 'PAN', 72, 2, 'regular'),
  (702, 'Team Photo', 'Panama', 'PAN', 72, 3, 'regular'),
  (703, 'Édgar Bárcenas', 'Panama', 'PAN', 72, 4, 'regular'),
  (704, 'Carlos Harvey', 'Panama', 'PAN', 72, 5, 'regular'),
  (705, 'Ismael Díaz', 'Panama', 'PAN', 72, 6, 'regular'),
  (706, 'Jose Fajardo', 'Panama', 'PAN', 72, 7, 'regular'),
  (707, 'Cecilio Waterman', 'Panama', 'PAN', 72, 8, 'regular'),
  (708, 'Jose Luiz Rodriguez', 'Panama', 'PAN', 72, 9, 'regular'),
  (709, 'Alberto Quintero', 'Panama', 'PAN', 72, 10, 'regular'),
  (710, 'Emblem', 'Paraguay', 'PAR', 73, 1, 'regular'),
  (711, 'Roberto Fernandez', 'Paraguay', 'PAR', 73, 2, 'regular'),
  (712, 'Orlando Gill', 'Paraguay', 'PAR', 73, 3, 'regular'),
  (713, 'Gustavo Gomez', 'Paraguay', 'PAR', 73, 4, 'regular'),
  (714, 'Fabián Balbuena', 'Paraguay', 'PAR', 73, 5, 'regular'),
  (715, 'Juan José Cáceres', 'Paraguay', 'PAR', 73, 6, 'regular'),
  (716, 'Omar Alderete', 'Paraguay', 'PAR', 73, 7, 'regular'),
  (717, 'Junior Alonso', 'Paraguay', 'PAR', 73, 8, 'regular'),
  (718, 'Mathías Villasanti', 'Paraguay', 'PAR', 73, 9, 'regular'),
  (719, 'Diego Gomez', 'Paraguay', 'PAR', 73, 10, 'regular'),
  (720, 'Damián Bobadilla', 'Paraguay', 'PAR', 74, 1, 'regular'),
  (721, 'Andres Cubas', 'Paraguay', 'PAR', 74, 2, 'regular'),
  (722, 'Team Photo', 'Paraguay', 'PAR', 74, 3, 'regular'),
  (723, 'Matias Galarza Fonda', 'Paraguay', 'PAR', 74, 4, 'regular'),
  (724, 'Julio Enciso', 'Paraguay', 'PAR', 74, 5, 'regular'),
  (725, 'Alejandro Romero Gamarra', 'Paraguay', 'PAR', 74, 6, 'regular'),
  (726, 'Miguel Almirón', 'Paraguay', 'PAR', 74, 7, 'regular'),
  (727, 'Ramon Sosa', 'Paraguay', 'PAR', 74, 8, 'regular'),
  (728, 'Angel Romero', 'Paraguay', 'PAR', 74, 9, 'regular'),
  (729, 'Antonio Sanabria', 'Paraguay', 'PAR', 74, 10, 'regular'),
  (730, 'Emblem', 'Portugal', 'POR', 75, 1, 'regular'),
  (731, 'Diogo Costa', 'Portugal', 'POR', 75, 2, 'regular'),
  (732, 'Jose Sa', 'Portugal', 'POR', 75, 3, 'regular'),
  (733, 'Ruben Dias', 'Portugal', 'POR', 75, 4, 'regular'),
  (734, 'João Cancelo', 'Portugal', 'POR', 75, 5, 'regular'),
  (735, 'Diogo Dalot', 'Portugal', 'POR', 75, 6, 'regular'),
  (736, 'Nuno Mendes', 'Portugal', 'POR', 75, 7, 'regular'),
  (737, 'Gonçalo Inácio', 'Portugal', 'POR', 75, 8, 'regular'),
  (738, 'Bernardo Silva', 'Portugal', 'POR', 75, 9, 'regular'),
  (739, 'Bruno Fernandes', 'Portugal', 'POR', 75, 10, 'regular'),
  (740, 'Ruben Neves', 'Portugal', 'POR', 76, 1, 'regular'),
  (741, 'Vitinha', 'Portugal', 'POR', 76, 2, 'regular'),
  (742, 'Team Photo', 'Portugal', 'POR', 76, 3, 'regular'),
  (743, 'João Neves', 'Portugal', 'POR', 76, 1, 'regular'),
  (744, 'Cristiano Ronaldo', 'Portugal', 'POR', 76, 5, 'regular'),
  (745, 'Francisco Trincao', 'Portugal', 'POR', 76, 6, 'regular'),
  (746, 'João Felix', 'Portugal', 'POR', 76, 7, 'regular'),
  (747, 'Gonçalo Ramos', 'Portugal', 'POR', 76, 8, 'regular'),
  (748, 'Pedro Neto', 'Portugal', 'POR', 76, 9, 'regular'),
  (749, 'Rafael Leão', 'Portugal', 'POR', 76, 10, 'regular'),
  (750, 'Emblem', 'Qatar', 'QAT', 77, 1, 'regular'),
  (751, 'Meshaal Barsham', 'Qatar', 'QAT', 77, 2, 'regular'),
  (752, 'Sultan Albrake', 'Qatar', 'QAT', 77, 3, 'regular'),
  (753, 'Lucas Mendes', 'Qatar', 'QAT', 77, 4, 'regular'),
  (754, 'Homam Ahmed', 'Qatar', 'QAT', 77, 5, 'regular'),
  (755, 'Boualem Khoukhi', 'Qatar', 'QAT', 77, 6, 'regular'),
  (756, 'Pedro Miguel', 'Qatar', 'QAT', 77, 7, 'regular'),
  (757, 'Tarek Salman', 'Qatar', 'QAT', 77, 8, 'regular'),
  (758, 'Mohamed Al-Mannai', 'Qatar', 'QAT', 77, 9, 'regular'),
  (759, 'Karim Boudiaf', 'Qatar', 'QAT', 77, 10, 'regular'),
  (760, 'Assim Madibo', 'Qatar', 'QAT', 78, 1, 'regular'),
  (761, 'Ahmed Fatehi', 'Qatar', 'QAT', 78, 2, 'regular'),
  (762, 'Team Photo', 'Qatar', 'QAT', 78, 3, 'regular'),
  (763, 'Mohammed Waad', 'Qatar', 'QAT', 78, 4, 'regular'),
  (764, 'Abdulaziz Hatem', 'Qatar', 'QAT', 78, 5, 'regular'),
  (765, 'Hassan Al-Haydos', 'Qatar', 'QAT', 78, 6, 'regular'),
  (766, 'Edmilson Junior', 'Qatar', 'QAT', 78, 7, 'regular'),
  (767, 'Akram Hassan Afif', 'Qatar', 'QAT', 78, 8, 'regular'),
  (768, 'Ahmed Al Ganehi', 'Qatar', 'QAT', 78, 9, 'regular'),
  (769, 'Almoez Ali', 'Qatar', 'QAT', 78, 10, 'regular'),
  (770, 'Emblem', 'South Africa', 'RSA', 79, 1, 'regular'),
  (771, 'Ronwen Williams', 'South Africa', 'RSA', 79, 2, 'regular'),
  (772, 'Sipho Chaine', 'South Africa', 'RSA', 79, 3, 'regular'),
  (773, 'Aubrey Modiba', 'South Africa', 'RSA', 79, 4, 'regular'),
  (774, 'Samukele Kabini', 'South Africa', 'RSA', 79, 5, 'regular'),
  (775, 'Mbekezeli Mbokazi', 'South Africa', 'RSA', 79, 6, 'regular'),
  (776, 'Khulumani Ndamane', 'South Africa', 'RSA', 79, 7, 'regular'),
  (777, 'Siyabonga Ngezana', 'South Africa', 'RSA', 79, 8, 'regular'),
  (778, 'Khuliso Mudau', 'South Africa', 'RSA', 79, 9, 'regular'),
  (779, 'Nkosinathi Sibisi', 'South Africa', 'RSA', 79, 10, 'regular'),
  (780, 'Teboho Mokoena', 'South Africa', 'RSA', 80, 1, 'regular'),
  (781, 'Thalente Mbatha', 'South Africa', 'RSA', 80, 2, 'regular'),
  (782, 'Team Photo', 'South Africa', 'RSA', 80, 3, 'regular'),
  (783, 'Bathasi Aubaas', 'South Africa', 'RSA', 80, 4, 'regular'),
  (784, 'Yaya Sithole', 'South Africa', 'RSA', 80, 5, 'regular'),
  (785, 'Sipho Mbule', 'South Africa', 'RSA', 80, 6, 'regular'),
  (786, 'Lyle Foster', 'South Africa', 'RSA', 80, 7, 'regular'),
  (787, 'Iqraam Rayners', 'South Africa', 'RSA', 80, 8, 'regular'),
  (788, 'Mohau Nkota', 'South Africa', 'RSA', 80, 9, 'regular'),
  (789, 'Oswin Appollis', 'South Africa', 'RSA', 80, 10, 'regular'),
  (790, 'Emblem', 'Scotland', 'SCO', 81, 1, 'regular'),
  (791, 'Angus Gunn', 'Scotland', 'SCO', 81, 2, 'regular'),
  (792, 'Jack Hendry', 'Scotland', 'SCO', 81, 3, 'regular'),
  (793, 'Kieran Tierney', 'Scotland', 'SCO', 81, 4, 'regular'),
  (794, 'Aaron Hickey', 'Scotland', 'SCO', 81, 5, 'regular'),
  (795, 'Andrew Robertson', 'Scotland', 'SCO', 81, 6, 'regular'),
  (796, 'Scott McKenna', 'Scotland', 'SCO', 81, 7, 'regular'),
  (797, 'John Souttar', 'Scotland', 'SCO', 81, 8, 'regular'),
  (798, 'Anthony Ralston', 'Scotland', 'SCO', 81, 9, 'regular'),
  (799, 'Grant Hanley', 'Scotland', 'SCO', 81, 10, 'regular'),
  (800, 'Scott McTominay', 'Scotland', 'SCO', 82, 1, 'regular'),
  (801, 'Billy Gilmour', 'Scotland', 'SCO', 82, 2, 'regular'),
  (802, 'Team Photo', 'Scotland', 'SCO', 82, 3, 'regular'),
  (803, 'Lewis Ferguson', 'Scotland', 'SCO', 82, 4, 'regular'),
  (804, 'Ryan Christie', 'Scotland', 'SCO', 82, 5, 'regular'),
  (805, 'Kenny McLean', 'Scotland', 'SCO', 82, 6, 'regular'),
  (806, 'John McGinn', 'Scotland', 'SCO', 82, 7, 'regular'),
  (807, 'Lyndon Dykes', 'Scotland', 'SCO', 82, 8, 'regular'),
  (808, 'Che Adams', 'Scotland', 'SCO', 82, 9, 'regular'),
  (809, 'Ben Gannon-Doak', 'Scotland', 'SCO', 82, 10, 'regular'),
  (810, 'Emblem', 'Senegal', 'SEN', 83, 1, 'regular'),
  (811, 'Eduardo Mendy', 'Senegal', 'SEN', 83, 2, 'regular'),
  (812, 'Yehvann Diouf', 'Senegal', 'SEN', 83, 3, 'regular'),
  (813, 'Moussa Niakhaté', 'Senegal', 'SEN', 83, 4, 'regular'),
  (814, 'Abdoulaye Seck', 'Senegal', 'SEN', 83, 5, 'regular'),
  (815, 'Ismail Jakobs', 'Senegal', 'SEN', 83, 6, 'regular'),
  (816, 'El Hadji Malick Diouf', 'Senegal', 'SEN', 83, 7, 'regular'),
  (817, 'Kalidou Koulibaly', 'Senegal', 'SEN', 83, 8, 'regular'),
  (818, 'Idrissa Gana Gueye', 'Senegal', 'SEN', 83, 9, 'regular'),
  (819, 'Pape Matar Sarr', 'Senegal', 'SEN', 83, 10, 'regular'),
  (820, 'Pape Gueye', 'Senegal', 'SEN', 84, 1, 'regular'),
  (821, 'Habib Diarra', 'Senegal', 'SEN', 84, 2, 'regular'),
  (822, 'Team Photo', 'Senegal', 'SEN', 84, 3, 'regular'),
  (823, 'Lamine Camara', 'Senegal', 'SEN', 84, 4, 'regular'),
  (824, 'Sadio Mane', 'Senegal', 'SEN', 84, 5, 'regular'),
  (825, 'Ismaïla Sarr', 'Senegal', 'SEN', 84, 6, 'regular'),
  (826, 'Boulaye Dia', 'Senegal', 'SEN', 84, 7, 'regular'),
  (827, 'Iliman Ndiaye', 'Senegal', 'SEN', 84, 8, 'regular'),
  (828, 'Nicolas Jackson', 'Senegal', 'SEN', 84, 9, 'regular'),
  (829, 'Krepin Diatta', 'Senegal', 'SEN', 84, 10, 'regular'),
  (830, 'Emblem', 'Switzerland', 'SUI', 85, 1, 'regular'),
  (831, 'Gregor Kobel', 'Switzerland', 'SUI', 85, 2, 'regular'),
  (832, 'Yvon Mvogo', 'Switzerland', 'SUI', 85, 3, 'regular'),
  (833, 'Manuel Akanji', 'Switzerland', 'SUI', 85, 4, 'regular'),
  (834, 'Ricardo Rodriguez', 'Switzerland', 'SUI', 85, 5, 'regular'),
  (835, 'Nico Elvedi', 'Switzerland', 'SUI', 85, 6, 'regular'),
  (836, 'Aurèle Amenda', 'Switzerland', 'SUI', 85, 7, 'regular'),
  (837, 'Silvan Widmer', 'Switzerland', 'SUI', 85, 8, 'regular'),
  (838, 'Granit Xhaka', 'Switzerland', 'SUI', 85, 9, 'regular'),
  (839, 'Denis Zakaria', 'Switzerland', 'SUI', 85, 10, 'regular'),
  (840, 'Remo Freuler', 'Switzerland', 'SUI', 86, 1, 'regular'),
  (841, 'Fabian Rieder', 'Switzerland', 'SUI', 86, 2, 'regular'),
  (842, 'Team Photo', 'Switzerland', 'SUI', 86, 3, 'regular'),
  (843, 'Ardon Jashari', 'Switzerland', 'SUI', 86, 4, 'regular'),
  (844, 'Johan Manzambi', 'Switzerland', 'SUI', 86, 5, 'regular'),
  (845, 'Michel Aebischer', 'Switzerland', 'SUI', 86, 6, 'regular'),
  (846, 'Breel Embolo', 'Switzerland', 'SUI', 86, 7, 'regular'),
  (847, 'Ruben Vargas', 'Switzerland', 'SUI', 86, 8, 'regular'),
  (848, 'Dan Ndoye', 'Switzerland', 'SUI', 86, 9, 'regular'),
  (849, 'Zeki Amdouni', 'Switzerland', 'SUI', 86, 10, 'regular'),
  (850, 'Emblem', 'Sweden', 'SWE', 87, 1, 'regular'),
  (851, 'Victor Johansson', 'Sweden', 'SWE', 87, 2, 'regular'),
  (852, 'Isak Hien', 'Sweden', 'SWE', 87, 3, 'regular'),
  (853, 'Gabriel Gudmundsson', 'Sweden', 'SWE', 87, 4, 'regular'),
  (854, 'Emil Holm', 'Sweden', 'SWE', 87, 5, 'regular'),
  (855, 'Victor Nilsson Lindelöf', 'Sweden', 'SWE', 87, 6, 'regular'),
  (856, 'Gustaf Lagerbielke', 'Sweden', 'SWE', 87, 7, 'regular'),
  (857, 'Lucas Bergvall', 'Sweden', 'SWE', 87, 8, 'regular'),
  (858, 'Hugo Larsson', 'Sweden', 'SWE', 87, 9, 'regular'),
  (859, 'Jesper Karlström', 'Sweden', 'SWE', 87, 10, 'regular'),
  (860, 'Yasin Ayari', 'Sweden', 'SWE', 88, 1, 'regular'),
  (861, 'Mattias Svanberg', 'Sweden', 'SWE', 88, 2, 'regular'),
  (862, 'Team Photo', 'Sweden', 'SWE', 88, 3, 'regular'),
  (863, 'Daniel Svensson', 'Sweden', 'SWE', 88, 4, 'regular'),
  (864, 'Ken Sema', 'Sweden', 'SWE', 88, 5, 'regular'),
  (865, 'Roony Bardghji', 'Sweden', 'SWE', 88, 6, 'regular'),
  (866, 'Dejan Kulusevski', 'Sweden', 'SWE', 88, 7, 'regular'),
  (867, 'Anthony Elanga', 'Sweden', 'SWE', 88, 8, 'regular'),
  (868, 'Alexander Isak', 'Sweden', 'SWE', 88, 9, 'regular'),
  (869, 'Viktor Gyökeres', 'Sweden', 'SWE', 88, 10, 'regular'),
  (870, 'Emblem', 'Tunisia', 'TUN', 89, 1, 'regular'),
  (871, 'Bechir Ben Said', 'Tunisia', 'TUN', 89, 2, 'regular'),
  (872, 'Aymen Dahmen', 'Tunisia', 'TUN', 89, 3, 'regular'),
  (873, 'Van Valery', 'Tunisia', 'TUN', 89, 4, 'regular'),
  (874, 'Montassar Talbi', 'Tunisia', 'TUN', 89, 5, 'regular'),
  (875, 'Yassine Meriah', 'Tunisia', 'TUN', 89, 6, 'regular'),
  (876, 'Ali Abdi', 'Tunisia', 'TUN', 89, 7, 'regular'),
  (877, 'Dylan Bronn', 'Tunisia', 'TUN', 89, 8, 'regular'),
  (878, 'Ellyes Skhiri', 'Tunisia', 'TUN', 89, 9, 'regular'),
  (879, 'Aissa Laidouni', 'Tunisia', 'TUN', 89, 10, 'regular'),
  (880, 'Ferjani Sassi', 'Tunisia', 'TUN', 90, 1, 'regular'),
  (881, 'Mohamed Ali Ben Romdhane', 'Tunisia', 'TUN', 90, 2, 'regular'),
  (882, 'Team Photo', 'Tunisia', 'TUN', 90, 3, 'regular'),
  (883, 'Hannibal Mejbri', 'Tunisia', 'TUN', 90, 4, 'regular'),
  (884, 'Elias Achouri', 'Tunisia', 'TUN', 90, 5, 'regular'),
  (885, 'Elias Saad', 'Tunisia', 'TUN', 90, 6, 'regular'),
  (886, 'Hazem Mastouri', 'Tunisia', 'TUN', 90, 7, 'regular'),
  (887, 'Ismael Gharbi', 'Tunisia', 'TUN', 90, 8, 'regular'),
  (888, 'Sayfallah Ltaief', 'Tunisia', 'TUN', 90, 9, 'regular'),
  (889, 'Naim Sliti', 'Tunisia', 'TUN', 90, 10, 'regular'),
  (890, 'Emblem', 'Türkiye', 'TUR', 91, 1, 'regular'),
  (891, 'Ugurcan Cakir', 'Türkiye', 'TUR', 91, 2, 'regular'),
  (892, 'Mert Muldur', 'Türkiye', 'TUR', 91, 3, 'regular'),
  (893, 'Zeki Celik', 'Türkiye', 'TUR', 91, 4, 'regular'),
  (894, 'Abdulkerim Bardakci', 'Türkiye', 'TUR', 91, 5, 'regular'),
  (895, 'Caglar Soyunku', 'Türkiye', 'TUR', 91, 6, 'regular'),
  (896, 'Merih Demiral', 'Türkiye', 'TUR', 91, 7, 'regular'),
  (897, 'Ferdi Kadioglu', 'Türkiye', 'TUR', 91, 8, 'regular'),
  (898, 'Kaan Ayhan', 'Türkiye', 'TUR', 91, 9, 'regular'),
  (899, 'Ismail Yuksek', 'Türkiye', 'TUR', 91, 10, 'regular'),
  (900, 'Hakan Calhanoglu', 'Türkiye', 'TUR', 92, 1, 'regular'),
  (901, 'Orkun Kokcu', 'Türkiye', 'TUR', 92, 2, 'regular'),
  (902, 'Team Photo', 'Türkiye', 'TUR', 92, 3, 'regular'),
  (903, 'Arda Guler', 'Türkiye', 'TUR', 92, 4, 'regular'),
  (904, 'Irfan Can Kahvecu', 'Türkiye', 'TUR', 92, 5, 'regular'),
  (905, 'Yunus Akgun', 'Türkiye', 'TUR', 92, 6, 'regular'),
  (906, 'Can Uzun', 'Türkiye', 'TUR', 92, 7, 'regular'),
  (907, 'Baris Alper Yilmaz', 'Türkiye', 'TUR', 92, 8, 'regular'),
  (908, 'Kerem Akturkoglu', 'Türkiye', 'TUR', 92, 9, 'regular'),
  (909, 'Kenan Yildiz', 'Türkiye', 'TUR', 92, 10, 'regular'),
  (910, 'Emblem', 'Uruguay', 'URU', 93, 1, 'regular'),
  (911, 'Sergio Rochet', 'Uruguay', 'URU', 93, 2, 'regular'),
  (912, 'Santiago Mele', 'Uruguay', 'URU', 93, 3, 'regular'),
  (913, 'Ronald Araujo', 'Uruguay', 'URU', 93, 4, 'regular'),
  (914, 'José María Giménez', 'Uruguay', 'URU', 93, 5, 'regular'),
  (915, 'Sebastian Caceres', 'Uruguay', 'URU', 93, 6, 'regular'),
  (916, 'Mathias Olivera', 'Uruguay', 'URU', 93, 7, 'regular'),
  (917, 'Guillermo Varela', 'Uruguay', 'URU', 93, 8, 'regular'),
  (918, 'Nahitan Nandez', 'Uruguay', 'URU', 93, 9, 'regular'),
  (919, 'Federico Valverde', 'Uruguay', 'URU', 93, 10, 'regular'),
  (920, 'Giorgian De Arrascaeta', 'Uruguay', 'URU', 94, 1, 'regular'),
  (921, 'Rodrigo Bentancur', 'Uruguay', 'URU', 94, 2, 'regular'),
  (922, 'Team Photo', 'Uruguay', 'URU', 94, 3, 'regular'),
  (923, 'Manuel Ugarte', 'Uruguay', 'URU', 94, 4, 'regular'),
  (924, 'Nicolás de la Cruz', 'Uruguay', 'URU', 94, 5, 'regular'),
  (925, 'Maxi Araujo', 'Uruguay', 'URU', 94, 6, 'regular'),
  (926, 'Darwin Núñez', 'Uruguay', 'URU', 94, 7, 'regular'),
  (927, 'Federico Viñas', 'Uruguay', 'URU', 94, 8, 'regular'),
  (928, 'Rodrigo Aguirre', 'Uruguay', 'URU', 94, 9, 'regular'),
  (929, 'Facundo Pellistri', 'Uruguay', 'URU', 94, 10, 'regular'),
  (930, 'Emblem', 'United States', 'USA', 95, 1, 'regular'),
  (931, 'Matt Freese', 'United States', 'USA', 95, 2, 'regular'),
  (932, 'Chris Richards', 'United States', 'USA', 95, 3, 'regular'),
  (933, 'Tim Ream', 'United States', 'USA', 95, 4, 'regular'),
  (934, 'Mark McKenzie', 'United States', 'USA', 95, 5, 'regular'),
  (935, 'Alex Freeman', 'United States', 'USA', 95, 6, 'regular'),
  (936, 'Antonee Robinson', 'United States', 'USA', 95, 7, 'regular'),
  (937, 'Tyler Adams', 'United States', 'USA', 95, 8, 'regular'),
  (938, 'Tanner Tessmann', 'United States', 'USA', 95, 9, 'regular'),
  (939, 'Weston McKennie', 'United States', 'USA', 95, 10, 'regular'),
  (940, 'Christian Roldan', 'United States', 'USA', 96, 1, 'regular'),
  (941, 'Timothy Weah', 'United States', 'USA', 96, 2, 'regular'),
  (942, 'Team Photo', 'United States', 'USA', 96, 3, 'regular'),
  (943, 'Diego Luna', 'United States', 'USA', 96, 4, 'regular'),
  (944, 'Malim Tillman', 'United States', 'USA', 96, 5, 'regular'),
  (945, 'Christian Pulisic', 'United States', 'USA', 96, 6, 'regular'),
  (946, 'Brenden Aaronson', 'United States', 'USA', 96, 7, 'regular'),
  (947, 'Ricardo Pepi', 'United States', 'USA', 96, 8, 'regular'),
  (948, 'Haji Wright', 'United States', 'USA', 96, 9, 'regular'),
  (949, 'Folarin Balogun', 'United States', 'USA', 96, 10, 'regular'),
  (950, 'Emblem', 'Uzbekistan', 'UZB', 97, 1, 'regular'),
  (951, 'Utkir Yusupov', 'Uzbekistan', 'UZB', 97, 2, 'regular'),
  (952, 'Farrukh Savfiev', 'Uzbekistan', 'UZB', 97, 3, 'regular'),
  (953, 'Sherzod Nasrullaev', 'Uzbekistan', 'UZB', 97, 4, 'regular'),
  (954, 'Umar Eshmurodov', 'Uzbekistan', 'UZB', 97, 5, 'regular'),
  (955, 'Husniddin Aliqulov', 'Uzbekistan', 'UZB', 97, 6, 'regular'),
  (956, 'Rustamjon Ashurmatov', 'Uzbekistan', 'UZB', 97, 7, 'regular'),
  (957, 'Khojiakbar Alijonov', 'Uzbekistan', 'UZB', 97, 8, 'regular'),
  (958, 'Abdukodir Khusanov', 'Uzbekistan', 'UZB', 97, 9, 'regular'),
  (959, 'Odiljon Hamrobekov', 'Uzbekistan', 'UZB', 97, 10, 'regular'),
  (960, 'Otabek Shukurov', 'Uzbekistan', 'UZB', 98, 1, 'regular'),
  (961, 'Jamshid Iskanderov', 'Uzbekistan', 'UZB', 98, 2, 'regular'),
  (962, 'Team Photo', 'Uzbekistan', 'UZB', 98, 3, 'regular'),
  (963, 'Azizbek Turgunboev', 'Uzbekistan', 'UZB', 98, 4, 'regular'),
  (964, 'Khojimat Erkinov', 'Uzbekistan', 'UZB', 98, 5, 'regular'),
  (965, 'Eldor Shomurodov', 'Uzbekistan', 'UZB', 98, 6, 'regular'),
  (966, 'Oston Urunov', 'Uzbekistan', 'UZB', 98, 7, 'regular'),
  (967, 'Jaloliddin Masharipov', 'Uzbekistan', 'UZB', 98, 8, 'regular'),
  (968, 'Igor Sergeev', 'Uzbekistan', 'UZB', 98, 9, 'regular'),
  (969, 'Abbosbek Fayzullaev', 'Uzbekistan', 'UZB', 98, 10, 'regular'),
  (970, 'Team Photo', 'Italy 1934', 'FWC', 99, 1, 'special'),
  (971, 'Team Photo', 'Uruguay 1950', 'FWC', 100, 1, 'special'),
  (972, 'Team Photo', 'West Germany 1954', 'FWC', 101, 1, 'special'),
  (973, 'Team Photo', 'Brazil 1962', 'FWC', 102, 1, 'special'),
  (974, 'Team Photo', 'West Germany 1974', 'FWC', 103, 1, 'special'),
  (975, 'Team Photo', 'Argentina 1986', 'FWC', 104, 1, 'special'),
  (976, 'Team Photo', 'Brazil 1994', 'FWC', 105, 1, 'special'),
  (977, 'Team Photo', 'Brazil 2002', 'FWC', 106, 1, 'special'),
  (978, 'Team Photo', 'Italy 2006', 'FWC', 107, 1, 'special'),
  (979, 'Team Photo', 'Germany 2014', 'FWC', 108, 1, 'special'),
  (980, 'Team Photo', 'Argentina 2022', 'FWC', 109, 1, 'special');